# Generated by Django 6.0.1 on 2026-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='PK', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='PKR', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deep_count',
            field=models.IntegerField(default=1),
        ),
    ]
