# Generated by Django 6.0.1 on 2026-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_country_alter_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='basic_count',
            field=models.IntegerField(default=15),
        ),
    ]
