# Generated by Django 6.0.1 on 2026-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_basic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='basic_count',
            field=models.IntegerField(default=0),
        ),
    ]
