# Generated by Django 6.0.1 on 2026-02-27 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingplan_billingsubscription_delete_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingPlan',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='BillingSubscription',
            new_name='Subscription',
        ),
    ]
