# Generated by Django 6.0.1 on 2026-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_billingplan_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
