# Generated by Django 6.0.1 on 2026-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='deep_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='mode',
            field=models.CharField(choices=[('basic', 'Basic RAG'), ('deep', 'Deep Analysis')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='auditor_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='paragraph_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
