# Generated by Django 6.0.1 on 2026-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatlog_user_alter_chatlog_deep_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='deep_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='mode',
            field=models.CharField(choices=[('basic', 'Basic RAG'), ('deep', 'Deep Analysis')], default='basic', max_length=10),
        ),
    ]
