# Generated by Django 6.0.1 on 2026-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
    ]
