# Generated by Django 6.0.1 on 2026-03-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
    ]
